import { notFound } from "next/navigation";
const pages = {
  rooms:{kicker:"Stay",title:"Rooms with nowhere else to be.",intro:"Twelve fictional rooms and cottages shaped around quiet, garden views and tactile comfort.",art:"☾",cards:[["The Fern","Garden Room · orchard-facing window seat · breakfast included"],["The Blue Moon","House Suite · deep-blue sitting room · soaking bath"],["The Dahlia","Private Cottage · terrace · outdoor copper tub"],["The Rowan","House Room · writing desk · garden courtyard"],["The Moth","Attic Room · dormer windows · late-evening light"],["The Rosehip","Garden Suite · private sitting room · terrace breakfast"]]},
  wellness:{kicker:"Rituals",title:"Return to your own rhythm.",intro:"A fictional wellness program built around warm water, herbal treatments and enough time between appointments.",art:"≈",cards:[["Moon Bath","90 minutes · mineral soak, scalp ritual and tea"],["Garden Massage","60 or 90 minutes · slow full-body treatment"],["Herbal Steam","45 minutes · private botanical steam and cool-down"],["Quiet Hour","A bookable room with tea, blankets and no agenda"]]},
  dining:{kicker:"At the table",title:"What the garden gives us.",intro:"A small seasonal dining concept with candlelight, local growers and clear reservation information.",art:"✿",cards:[["Garden Breakfast","Included for overnight guests · 7:30–10:30"],["Moonpetal Supper","Thursday–Sunday · seasonal set menu"],["Afternoon Tea","Friday–Sunday · advance reservation"],["Picnic Basket","Pre-order for garden or local walking routes"]]},
  experiences:{kicker:"Beyond the room",title:"Small plans for slow days.",intro:"Experiences are intentionally limited and clearly described so discovery never turns into an activity catalog.",art:"⌁",cards:[["Dawn garden walk","A quiet guided loop before breakfast."],["Ceramics afternoon","A small-group local studio visit."],["Night garden hour","Lantern walk and seasonal herbal tea."],["Village bicycle route","A mapped self-guided ride with picnic stops."]]},
  journal:{kicker:"Notes from the house",title:"Stories for before, during and after a stay.",intro:"An editorial content layer for garden notes, local guides, rituals and seasonal search discovery.",art:"✒",cards:[["What blooms after dark?","A garden note on evening flowers and low-light planting."],["The case for doing almost nothing","A short ritual for unstructured afternoons."],["A late-summer supper in three bowls","Seasonal menu storytelling."],["A quiet weekend without a car","A practical local itinerary concept."]]},
  events:{kicker:"Private gatherings",title:"Small celebrations, held gently.",intro:"A private-hire concept for intimate dinners, retreats and celebrations with transparent capacity and enquiry paths.",art:"◇",cards:[["Garden dinner","Up to 24 guests · private table and terrace."],["House retreat","Up to 18 overnight guests · exclusive-use concept."],["Elopement","Two to 12 guests · ceremony, supper and stay."],["Creative off-site","Up to 16 guests · meeting room, meals and garden time."]]},
  location:{kicker:"Find the house",title:"Close enough to arrive. Far enough to exhale.",intro:"Because Moonpetal House is fictional, this page demonstrates local information architecture without inventing a real address.",art:"⌖",cards:[["By rail","A real property would provide the nearest station, transfer time and taxi guidance."],["By car","Driving notes would include parking, EV charging and seasonal road considerations."],["Without a car","Local walking, bicycle and transfer options would be explicit rather than assumed."],["Around the house","A useful local guide would prioritize genuinely nearby places over keyword-stuffed lists."]]},
  contact:{kicker:"Contact",title:"Ask the house a question.",intro:"A portfolio contact-flow demonstration for pre-stay questions, dining, private events and accessibility needs.",art:"✉",cards:[]},
  book:{kicker:"Booking handoff",title:"Choose the shape of your stay.",intro:"A transparent demo booking flow showing hierarchy for dates, guests, room preference and special requirements without pretending to query real inventory.",art:"☽",cards:[]}
} as const;
type S=keyof typeof pages;
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug as S];if(!p)notFound();const form=slug==="contact"||slug==="book";return <div className="subpage-shell"><header className="subpage-header"><a className="mark" href="/"><span>☾</span> MOONPETAL HOUSE</a><nav className="subpage-nav"><a href="/rooms">Stay</a><a href="/wellness">Wellness</a><a href="/dining">Dining</a><a href="/experiences">Experiences</a><a href="/journal">Journal</a></nav><a href="/book">Book</a></header><main className="subpage-main"><section className="subpage-hero"><div><p className="subpage-kicker">{p.kicker}</p><h1>{p.title}</h1><p>{p.intro}</p></div><div className="subpage-art" aria-hidden="true">{p.art}</div></section>{form?<><form className="subpage-form" action="#">{slug==="book"?<><label>Arrival<input type="date" required /></label><label>Departure<input type="date" required /></label><label>Guests<select defaultValue="2"><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label>Room preference<select defaultValue="No preference"><option>No preference</option><option>The Fern</option><option>The Blue Moon</option><option>The Dahlia</option></select></label></>:<><label>Name<input autoComplete="name" required /></label><label>Email<input type="email" autoComplete="email" required /></label><label>Topic<select><option>Stay</option><option>Dining</option><option>Private event</option><option>Accessibility</option></select></label></>}<label>Notes<textarea /></label><button className="subpage-button" type="submit">Preview {slug==="book"?"availability":"message"} flow</button></form><p className="subpage-note">Portfolio demonstration only. No reservation, message or personal data is submitted.</p></>:<section className="subpage-grid">{p.cards.map(([title,copy],i)=><article className="subpage-card" key={title}><h2>{title}</h2><p>{copy}</p>{slug==="rooms"&&i<3?<a href={i===0?"/room/the-fern":i===1?"/room/the-blue-moon":"/room/the-dahlia"}>View room →</a>:null}</article>)}</section>}<aside className="subpage-cta"><div><p className="subpage-kicker">Moonpetal House</p><h2>Stay somewhere softer.</h2></div><a href="/book">Explore booking</a></aside></main><footer className="subpage-footer"><span>Fictional hospitality concept by Brianna Dickenson.</span><a href="/">Back home</a></footer></div>}
