import { notFound } from "next/navigation";
const products = {
  "meadow-lark-pendant": ["Meadow Lark Pendant","$68","Jewelry","A slim brushed-gold concept pendant built around wing-like negative space and a tiny rose stone.","♢"],
  "fawn-frame-mini": ["Fawn Frame Mini","$148","Bag","A structured concept mini bag with softly curved hardware, cocoa lining and a detachable ribbon charm.","✦"],
  "night-finch-silk": ["Night Finch Silk","$86","Scarf","A washed-silk concept scarf using feather rhythm, fern shapes and plum night color.","❦"]
} as const;
type P=keyof typeof products;
export function generateStaticParams(){return Object.keys(products).map(slug=>({slug}));}
export default async function Product({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products[slug as P];if(!p)notFound();return <div className="subpage-shell"><header className="subpage-header"><a className="wordmark" href="/">FAWN <span>&</span> FINCH</a><nav className="subpage-nav"><a href="/collection">Collection</a><a href="/about">Our world</a><a href="/journal">Journal</a></nav><a href="/bag">Bag</a></header><main className="subpage-main"><section className="subpage-hero"><div><p className="subpage-kicker">{p[2]}</p><h1>{p[0]}</h1><p>{p[3]}</p><h2>{p[1]}</h2><a className="subpage-button" href="/bag">Add to concept bag</a><p className="subpage-note">Fictional product. No purchase is available.</p></div><div className="subpage-art" aria-hidden="true">{p[4]}</div></section><section className="subpage-grid"><article className="subpage-card"><h2>Material direction</h2><p>Brushed metal, softly tactile surfaces and restrained animal references.</p></article><article className="subpage-card"><h2>Product clarity</h2><p>Price, category, description, care and returns are surfaced before checkout intent.</p></article><article className="subpage-card"><h2>Responsive commerce</h2><p>The layout collapses to a single reading path on small screens without hiding purchase context.</p></article></section></main><footer className="subpage-footer"><span>Self-directed concept.</span><a href="/collection">Back to collection</a></footer></div>}
